### ISSUE TITLE
feat: change router to dynamic 

### ISSUE THREAD

**Issue by ONLY-yours** [shit-wu/Blog#17]
使用 `/?:sourceType` 的方式制定规定文章
可以动态去跳转router的方式会不会更好呀。

**Comment by shitshitme** [comment]
你指的是使用query这种传参方式使得url出现`/article?articleid=xxxxx`这种效果吗?

**Comment by shit-wu** [comment]
> 使用 `/?:sourceType` 的方式制定规定文章
> 可以动态去跳转router的方式会不会更好呀。

我之前忘记把我最新的代码推上去了，你看的是很久之前的静态版本，误会解除，我后面写的就是动态传参
